routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pesquisa/{id}', 'HomeController@survey')->name('pesquisa');
Route::post('/sendForm', ['as'=>'sendForm', 'uses'=>'HomeController@sendForm']);

Route::resource('surveys', 'SurveyController');

Route::resource('question_categories', 'QuestionCategoryController');

Route::resource('questions', 'QuestionController');

Route::resource('results', 'ResultController');

Route::resource('reports', 'ReportController');
Route::get('/reports/survey/{id}', 'ReportController@surveyReport')->name('report.surveyReport');
Route::get('/reports/question/{id}', 'ReportController@questionsReport')->name('report.questionsReport');

app/QuestionCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class QuestionCategory extends Model
{
    public $table = 'question_categories';
    public $timestamps = false;
    protected $fillable = ['name', 'priority'];
}

app/Http/Controllers/QuestionCategoryController.php
<?php

namespace App\Http\Controllers;

use App\QuestionCategory;
use Illuminate\Http\Request;

class QuestionCategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questionCategories = QuestionCategory::all();
        return view('questionCategories.index', compact('questionCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questionCategories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:question_categories'
        ]);
        QuestionCategory::create($request->all());
        return redirect()->route('question_categories.index')
            ->with('success', 'Categoria criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questionCategory = QuestionCategory::find($id);
        return view('questionCategories.edit',compact('questionCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|unique:surveys'
        ]);
        QuestionCategory::find($id)->update($request->all());
        return redirect()->route('question_categories.index')
                        ->with('success','Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        QuestionCategory::findOrFail($id)->delete();

        return redirect()->route('question_categories.index')
            ->with('success','Categoria deletada!');
    }
}

resources/views/questionCategories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading">Nova Categoria</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel-body">
                    {!! Form::open(['action' => 'QuestionCategoryController@store']) !!}
                        <?=Form::token();?>
                        <div class="form-group">
                            <?=Form::label('name', 'Nome');?>
                            <?=Form::text('name', null, ['class' => 'form-control']);?>
                        </div>
                        <div class="form-group">
                            <?=Form::label('priority', 'Prioridade');?>
                            <?php
                                echo Form::select('priority',[
                                '0' => 0,
                                '1' => 1,
                                '2' => 2,
                                '3' => 3,
                                '4' => 4,
                                '5' => 5,
                                '6' => 6,
                                '7' => 7,
                                '8' => 8,
                                '9' => 9,
                                '10' => 10,
                                ],
                                null,
                                ['class' => 'form-control']
                                );
                            ?>
                        </div>
                        <a href="{{ url('/question_categories') }}" class="btn btn-danger back">Voltar</a>
                        <?=Form::submit('Cadastrar', ['class' => 'btn btn-primary']);?>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questionCategories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading">Editar Categoria</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel-body">
                    {!! Form::model($questionCategory, ['method' => 'PATCH', 'route' => ['question_categories.update', $questionCategory->id]]) !!}
                        <?=Form::token();?>
                        <div class="form-group">
                            <?=Form::label('name', 'Nome');?>
                            <?=Form::text('name', null, ['class' => 'form-control']);?>
                        </div>
                        <div class="form-group">
                            <?=Form::label('priority', 'Prioridade');?>
                            <?php
                                echo Form::select('priority',[
                                '0' => 0,
                                '1' => 1,
                                '2' => 2,
                                '3' => 3,
                                '4' => 4,
                                '5' => 5,
                                '6' => 6,
                                '7' => 7,
                                '8' => 8,
                                '9' => 9,
                                '10' => 10,
                                ],
                                null,
                                ['class' => 'form-control']
                                );
                            ?>
                        </div>
                        <a href="{{ url('/question_categories') }}" class="btn btn-danger back">Voltar</a>
                        <?=Form::submit('Atualizar', ['class' => 'btn btn-primary']);?>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questionCategories/index.blade.php
@extends('layouts.app')

@section('content')
<? var_dump('success') ?>
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading">Categorias das perguntas <a href="{{ url('/question_categories/create') }}" class="add">Adicionar</a></div>
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel-body">
                    <table id="table" class="display table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Prioridade</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Prioridade</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>                    
                            @if($questionCategories)
                                @foreach($questionCategories as $questionCategory)
                                <tr>
                                    <td>{{ $questionCategory->id }}</td>
                                    <td>{{ $questionCategory->name }}</td>
                                    <td>{{ $questionCategory->priority }}</td>
                                    <td>
                                        <a href="{{ route('question_categories.edit',$questionCategory->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['question_categories.destroy', $questionCategory->id], 'class' => 'formDelete']) !!}

                                        {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i>', array('type' => 'submit', 'class' => 'delete')) !!}

                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @endforeach
                            @else
                                nada
                            @endif            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection