routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pesquisa/{id}', 'HomeController@survey')->name('pesquisa');
Route::post('/sendForm', ['as'=>'sendForm', 'uses'=>'HomeController@sendForm']);

Route::resource('surveys', 'SurveyController');

Route::resource('question_categories', 'QuestionCategoryController');

Route::resource('questions', 'QuestionController');

Route::resource('results', 'ResultController');

Route::resource('reports', 'ReportController');
Route::get('/reports/survey/{id}', 'ReportController@surveyReport')->name('report.surveyReport');
Route::get('/reports/question/{id}', 'ReportController@questionsReport')->name('report.questionsReport');

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Answer;
use App\Person;
use App\Question;
use App\Result;
use App\Survey;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $counter = Result::count();
        $surveys = Survey::withCount('results')->get();
        $questions = Question::withCount('answers')->get();
        return view('reports.index', compact('counter', 'surveys', 'questions'));
    }

    public function surveyReport($survey_id){
        $survey = Survey::find($survey_id);
        return view('reports.survey', compact('survey'));
    }

    public function questionsReport($question_id){
        $question = Question::find($question_id);      
        $options = explode(PHP_EOL, $question->options);
        $optionsWithCounter = [];
        $qtd_answers = count($question->answers);
        foreach($options as $key=>$option){            
            $optionsWithCounter[$key]['option'] = $option;
            $optionsWithCounter[$key]['counter'] = 0;
            $optionsWithCounter[$key]['percentage'] = 0;
            foreach($question->answers as $answer){
               if($answer->answer == $option){
                   $optionsWithCounter[$key]['counter']++;             
               }
           }           
           $optionsWithCounter[$key]['percentage'] =  (($optionsWithCounter[$key]['counter'] * 100) / $qtd_answers);
           $optionsWithCounter[$key]['percentage'] = number_format((float)$optionsWithCounter[$key]['percentage'], 2, '.', '');
        }        
        return view('reports.question', compact('question', 'optionsWithCounter'));
    }
}

resources/views/reports/index.blade.php
@extends('layouts.app')

@section('content')
<? var_dump('success') ?>
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading">Relatórios</div>
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel-body">
                    <h2>Pesquisas</h2>
                    <h5>Quantidade de pesquisas realizadas: {{ $counter }}</h5>
                    <table id="table" class="display table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Quantidade de respostas</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Quantidade de respostas</th>
                            </tr>
                        </tfoot>
                        <tbody>                    
                            @if($surveys)
                                @foreach($surveys as $survey)
                                <tr>
                                    <td>{{ $survey->name }}</td>
                                    <td>{{ $survey->results_count }}</td>
                                    <!--<td>
                                        <a href="{{ route('report.surveyReport', $survey->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    </td>-->
                                </tr>                                    
                                @endforeach
                            @else
                                nada
                            @endif            
                        </tbody>
                    </table>
                    <h2>Respostas de cada pergunta</h2>
                    <table id="table2" class="display table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Titulo da Pergunta</th>
                                <th>Quantidade de respostas</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Titulo da Pergunta</th>
                                <th>Quantidade de respostas</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>                    
                            @if($surveys)
                                @foreach($questions as $question)
                                <tr>
                                    <td>{{ $question->title }}</td>
                                    <td>{{ $question->answers_count }}</td>
                                    <td>
                                        <a href="{{ route('report.questionsReport', $question->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    </td>
                                </tr>                                    
                                @endforeach
                            @else
                                nada
                            @endif            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reports/question.blade.php
@extends('layouts.app')

@section('content')
<? var_dump('success') ?>
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9 show">
            <div class="panel panel-default">
                <div class="panel-heading">Relatórios - Pergunta</div>
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel-body">
                    <h2>{{ $question->title }}</h2>
                    <div class="row">
                        @foreach($optionsWithCounter as $option)
                            <div class="col-lg-4 col-md-6 col-sm-12">
                                <h3>{{ $option["option"] }}</h3>
                                <p>{{ $option["counter"] }} - {{ $option["percentage"] }}%</p>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reports/survey.blade.php
@extends('layouts.app')

@section('content')
<? var_dump('success') ?>
<div class="container">
    <div class="row">        
        @include('shared.sidebar')
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading">Relatórios</div>
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel-body">
                    <h2>Pesquisas</h2>
                    <h5>Quantidade de pesquisas realizadas: {{ $counter }}</h5>
                    <table id="table" class="display table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Quantidade de respostas</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Quantidade de respostas</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>                    
                            @if($surveys->questions)
                                @foreach($surveys->questions as $questions)
                                <tr>
                                    <td>{{ $survey->title }}</td>
                                    <td>{{ $survey->results_count }}</td>
                                    <td>
                                        <a href="{{ route('report.surveyReport', $survey->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    </td>
                                </tr>                                    
                                @endforeach
                            @else
                                nada
                            @endif            
                        </tbody>
                    </table>                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection